### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by kastentx** [IBM/MAX-Image-Segmenter-Web-App#5]
- [x] Install guide
- [x] Diagrams
- [ ] Code Pattern documentation
- [x] Demo video

**Comment by ajbozarth** [comment]
I'll add comments here for Doc related issues rather than opening new issues:

- [ ] Add a README for the assets directory similar to how models do it (including a license, etc)
- [ ] Update wiki according to feedback from IBM Developer team (@rhagarty would know what needs updating better than me)
- [ ] Update title in README to match wiki (once it's approved by @rhagarty )

**Comment by ajbozarth** [comment]
@rhagarty could you take a look at the README and the wiki page and comment here anything remaining that needs to be addressed before we can move this into publishing?
